// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mocuuthljiirxaisuolc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vY3V1dGhsamlpcnhhaXN1b2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MjkyNzMsImV4cCI6MjA1MTAwNTI3M30.iETkYt3UeyqUGbtB1dQ4l4xLDNL9WE5bYV4GaeDCc1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);